import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import { TheHeader } from "@/app/ui/TheHeader";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth/types";
import { ReactQueryProvider } from "./utils/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />

        <SessionProvider session={session}>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
