import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import { TheHeader } from "@/app/ui/TheHeader";
import { ReactQueryProvider } from "./utils/ReactQueryProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
